name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Inject API Key at Runtime Without Committing
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          mkdir -p dist
          echo "<script>window.API_KEY = '${{ secrets.API_KEY }}';</script>" > dist/config.js

      - name: Build Site
        run: |
          cp -r * dist/
          rm -rf dist/.github

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
