name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          mkdir -p dist/js
          cp -r * dist/
          sed -i "s|__API_KEY__|$API_KEY|g" dist/js/script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
